### ISSUE TITLE
Tooltip 2.0.2 console warnings

### ISSUE THREAD

**Issue by msimonc** [WTTJ/welcome-ui#814]
Tooltip 2.0.2 works perfectly but React shows this in the console...

react-dom.development.js?17ef:67 Warning: Received `true` for a non-boolean attribute `modal`.

If you want to write it to the DOM, pass a string instead: modal="true" or modal={value.toString()}.
    at span
    at TooltipReference (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:47:26)
    at eval (webpack-internal:///../../node_modules/@welcome-ui/tooltip/dist/tooltip.es.js:163:24)
    at CodeText
    at div
    at Styled(div)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at Gi (webpack-internal:///../seeker-shared/dist/index.js:2:65610)
    at DashboardComp (webpack-internal:///./components/Dash/DashboardComp.tsx:55:23)
    at Dash (webpack-internal:///./pages/dashboard/index.tsx:22:14)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at HideFocusRingsRoot (webpack-internal:///../../node_modules/@welcome-ui/utils/dist/utils.es.js:190:23)
    at Ge (webpack-internal:///../../node_modules/styled-components/dist/styled-components.browser.esm.js:28:17052)
    at WuiProvider (webpack-internal:///../../node_modules/@welcome-ui/core/dist/core.es.js:1735:23)
    at LayoutComp (webpack-internal:///./components/Layout/index.tsx:76:94)
    at Connect(LayoutComp) (webpack-internal:///../../node_modules/react-redux/es/components/connectAdvanced.js:231:75)
    at WrappedApp (webpack-internal:///./pages/_app.tsx:55:94)
    at Provider (webpack-internal:///../../node_modules/react-redux/es/components/Provider.js:14:20)
    at withRedux(WrappedApp) (webpack-internal:///../../node_modules/next-redux-wrapper/es6/index.js:182:35)
    at ErrorBoundary (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:151:5)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:642:24)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:771:24)
printWarning @ react-dom.development.js?17ef:67
error @ react-dom.development.js?17ef:43
validateProperty$1 @ react-dom.development.js?17ef:3521
warnUnknownProperties @ react-dom.development.js?17ef:3559
validateProperties$2 @ react-dom.development.js?17ef:3583
validatePropertiesInDevelopment @ react-dom.development.js?17ef:8765
setInitialProperties @ react-dom.development.js?17ef:9041
finalizeInitialChildren @ react-dom.development.js?17ef:10201
completeWork @ react-dom.development.js?17ef:19470
completeUnitOfWork @ react-dom.development.js?17ef:22815
performUnitOfWork @ react-dom.development.js?17ef:22787
workLoopSync @ react-dom.development.js?17ef:22707
renderRootSync @ react-dom.development.js?17ef:22670
performSyncWorkOnRoot @ react-dom.development.js?17ef:22293
eval @ react-dom.development.js?17ef:11327
unstable_runWithPriority @ scheduler.development.js?f758:646
runWithPriority$1 @ react-dom.development.js?17ef:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?17ef:11322
flushSyncCallbackQueue @ react-dom.development.js?17ef:11309
scheduleUpdateOnFiber @ react-dom.development.js?17ef:21893
enqueueSetState @ react-dom.development.js?17ef:12467
Component.setState @ react.development.js?8286:365
_callee2$ @ index.tsx?fa80:58
tryCatch @ runtime.js?6a3c:63
invoke @ runtime.js?6a3c:293
eval @ runtime.js?6a3c:118
asyncGeneratorStep @ asyncToGenerator.js?bce6:3
_next @ asyncToGenerator.js?bce6:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?bce6:13
_next @ asyncToGenerator.js?bce6:25
eval @ asyncToGenerator.js?bce6:32
eval @ asyncToGenerator.js?bce6:21
componentDidUpdate @ index.tsx?fa80:31
commitLifeCycles @ react-dom.development.js?17ef:20684
commitLayoutEffects @ react-dom.development.js?17ef:23426
callCallback @ react-dom.development.js?17ef:3945
invokeGuardedCallbackDev @ react-dom.development.js?17ef:3994
invokeGuardedCallback @ react-dom.development.js?17ef:4056
commitRootImpl @ react-dom.development.js?17ef:23151
unstable_runWithPriority @ scheduler.development.js?f758:646
runWithPriority$1 @ react-dom.development.js?17ef:11276
commitRoot @ react-dom.development.js?17ef:22990
performSyncWorkOnRoot @ react-dom.development.js?17ef:22329
eval @ react-dom.development.js?17ef:11327
unstable_runWithPriority @ scheduler.development.js?f758:646
runWithPriority$1 @ react-dom.development.js?17ef:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?17ef:11322
flushSyncCallbackQueue @ react-dom.development.js?17ef:11309
unbatchedUpdates @ react-dom.development.js?17ef:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js?17ef:26020
hydrate @ react-dom.development.js?17ef:26086
renderReactElement @ index.tsx?8abf:518
doRender @ index.tsx?8abf:776
_callee2$ @ index.tsx?8abf:413
tryCatch @ runtime.js?6a3c:63
invoke @ runtime.js?6a3c:293
eval @ runtime.js?6a3c:118
asyncGeneratorStep @ asyncToGenerator.js?7ee8:3
_next @ asyncToGenerator.js?7ee8:25
eval @ asyncToGenerator.js?7ee8:32
eval @ asyncToGenerator.js?7ee8:21
_render @ index.js:515
render @ index.js:452
eval @ next-dev.js?53bc:85
eval @ fouc.js?937a:14
requestAnimationFrame (async)
displayContent @ fouc.js?937a:5
eval @ next-dev.js?53bc:84
Promise.then (async)
eval @ next-dev.js?53bc:31
eval @ next-dev.js?53bc:31
../../node_modules/next/dist/client/next-dev.js @ main.js?ts=1610220176351:956
__webpack_require__ @ webpack.js?ts=1610220176351:873
checkDeferredModules @ webpack.js?ts=1610220176351:46
webpackJsonpCallback @ webpack.js?ts=1610220176351:33
(anonymous) @ webpack.js?ts=1610220176351:1015
(anonymous) @ webpack.js?ts=1610220176351:1023
Show 35 more frames
06:22:59.133 react-dom.development.js?17ef:67 Warning: React does not recognize the `setModal` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `setmodal` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at span
    at TooltipReference (webpack-internal:///../../node_modules/reakit-system/es/createComponent.js:47:26)
    at eval (webpack-internal:///../../node_modules/@welcome-ui/tooltip/dist/tooltip.es.js:163:24)
    at CodeText
    at div
    at Styled(div)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at Gi (webpack-internal:///../seeker-shared/dist/index.js:2:65610)
    at DashboardComp (webpack-internal:///./components/Dash/DashboardComp.tsx:55:23)
    at Dash (webpack-internal:///./pages/dashboard/index.tsx:22:14)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at HideFocusRingsRoot (webpack-internal:///../../node_modules/@welcome-ui/utils/dist/utils.es.js:190:23)
    at Ge (webpack-internal:///../../node_modules/styled-components/dist/styled-components.browser.esm.js:28:17052)
    at WuiProvider (webpack-internal:///../../node_modules/@welcome-ui/core/dist/core.es.js:1735:23)
    at LayoutComp (webpack-internal:///./components/Layout/index.tsx:76:94)
    at Connect(LayoutComp) (webpack-internal:///../../node_modules/react-redux/es/components/connectAdvanced.js:231:75)
    at WrappedApp (webpack-internal:///./pages/_app.tsx:55:94)
    at Provider (webpack-internal:///../../node_modules/react-redux/es/components/Provider.js:14:20)
    at withRedux(WrappedApp) (webpack-internal:///../../node_modules/next-redux-wrapper/es6/index.js:182:35)
    at ErrorBoundary (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:151:5)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:642:24)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:771:24)

**Comment by theo-mesnil** [comment]
Hi @msimonc :) Thanks for your feedback we are going to watch this !

**Comment by theo-mesnil** [comment]
Hi @msimonc , i think it's from Reakit:
- https://github.com/reakit/reakit/pull/802
- https://github.com/reakit/reakit/issues/656

**Comment by theo-mesnil** [comment]
A close this issue, i hove the new v4 version will fix this.
